name: Node.js Package
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          # Defaults to the user or organization that owns the workflow file
          # scope: '@octocat'
      - run: npm ci
      - run: npm run build
      - run: npm run coverage
      - run: npm run lint
